### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by ashwani99**

### CODE REVIEW

**Comment by Osmose** [comment]
Thanks for the PR!

**Comment by ashwani99** [comment]
@Osmose Thanks for the encouragement. I'm new here and want to start proper contributing. Can you help me to get started? I know this may not the right place to ask this but I'm so confused.

**Comment by Osmose** [comment]
No problem!

There's [whatcanidoformozilla.org](http://whatcanidoformozilla.org) for finding interesting projects in Mozilla. For webdev in particular, there's a [New Contributor Guide](http://mozweb.readthedocs.io/en/latest/guide/index.html) for people who are interested in starting to contribute to Mozilla Webdev. 

If you have a specific language or technology you're interested in contributing with, I can also help suggest projects to look into.

**Comment by ashwani99** [comment]
Any beginner friendly python projects?

**Comment by Osmose** [comment]
Sure! I'm told that Servo has some good first python bugs to look into: https://starters.servo.org/

**Pull request merged**
