### PR TITLE
Add template for Beer and Tell and June 2015 post.

### PR DESCRIPTION
**Pull request by Osmose**
@pelmers @erikrose @potch @peterbe r? on the actual blog post?

@erikrose in particular, I couldn't come up with a good summary of your points, could you comment with a paragraph or two on your tips for people running their own email servers?

I'm hoping to post this sometime this weekend or Monday at the latest, ya'll should respond before then. Thanks!

### CODE REVIEW

**Comment by pelmers** [comment]
r+ on my section

**Comment by peterbe** [comment]
r+

**Comment by Osmose** [comment]
I removed @erikrose's entry and merged. I'm happy to edit and add that section back in if you still want it included. :D
Thanks all!

**Comment by erikrose** [comment]
Erik Rose learned a lot about the current state of spam-fighting while redoing his mail server:

* Telling Postfix to be picky about RFCs is a good first pass. It eliminates some spam without having to do much computation.
* spamassassin beats out dspam, which hasn't seen an update since 2012.
* Shared-digest detectors like Razor help a bit but aren't sufficient on their own without also greylisting to give the DBs a chance to catch up.
* DNS blocklists are a great aid: they reject 3 out of 4 spams without taking much CPU.
* Bayes is still the most reliable (though the most CPU-intense) filtration method. Bayes poisoning is infeasible, because poisoners don't know what your ham looks like, so don't worry about hand-picking spam to train on. Train on an equal number of spams and hams: 400 of each works well. Once your bayes is performing well, crank up your BAYES_nn settings so spamassassin believes it.
* Crank up spamc's --max-size to 1024000, because spammers are now attaching images > 512K to mails to bypass spamc's stock 512K threshold. This will cost extra CPU.

With this, I get perhaps a spam a week, with over 400 attempts per day.

**Pull request merged**
